export const tableData = [
  {
    id: 1,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 2,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 3,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 4,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 5,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 6,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 7,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 8,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 9,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 10,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 11,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
  {
    id: 12,
    tName: "John Doe",
    tId: "123456",
    department: "Computer Science",
    student: "50",
    status: "Active",
    allDetails: "View More",
  },
];
